# Generated by Django 3.2.5 on 2022-06-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0003_auto_20220602_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Putovanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('slika', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=900)),
                ('tip', models.CharField(max_length=100)),
                ('grad', models.CharField(max_length=200)),
                ('pocetak', models.DateField(blank=True, null=True)),
                ('kraj', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
