# Generated by Django 3.2.5 on 2022-06-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0006_putovanja_korisnik_agencija'),
    ]

    operations = [
        migrations.AddField(
            model_name='putovanje',
            name='organizator_putovanja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='putovanja.agencija'),
        ),
        migrations.AlterField(
            model_name='putovanja_korisnik_agencija',
            name='agencija_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putovanja.putovanje'),
        ),
    ]
