# Generated by Django 3.2.5 on 2022-06-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0007_auto_20220606_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='putovanja_korisnik_agencija',
            old_name='agencija_id',
            new_name='putovanje_id',
        ),
    ]
