# Generated by Django 3.2.5 on 2022-06-06 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('putovanja', '0008_rename_agencija_id_putovanja_korisnik_agencija_putovanje_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putovanja_korisnik_agencija',
            name='korisnik_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
