# Generated by Django 3.2.5 on 2022-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0011_alter_putovanje_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='datum_osnivanja',
            field=models.DateField(blank=True, default='2000-05-04', null=True),
        ),
    ]
