# Generated by Django 3.2.5 on 2022-06-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putovanja', '0012_alter_korisnik_datum_osnivanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='putovanje',
            name='predlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='putovanje',
            name='tip',
            field=models.CharField(default='Organizovano', max_length=100),
        ),
    ]
