# Generated by Django 3.2.5 on 2022-05-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datum_osnivanja',
            field=models.CharField(default='14/7/2008', max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='id_agencije',
            field=models.IntegerField(default=0),
        ),
    ]
